name: Deploy static content

on:
  push:
    branches:
      - main
jobs:
  deploy-static-content:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '20.7.0'

      - name: Install
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: ITl0ver/Passenger-Traffic-Analyzer@v4
        with:
          folder: build
          branch: gh-pages
