
name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref  }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache dependencies
      uses: actions/cache@v3
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  
        restore-keys: | 
          ${{ runner.os }}-node-

    - run: |
        sed -i  "homepage": "https://github.com/ITl0ver/Passenger-Traffic-Analyzer", ./package.json
    - run: npm ci
    - run: npm run build
    - run: cp build/index.html build/404.html

    - name: Deploy
      uses: Passenger-Traffic-Analyzer/actions-gh-pages@v2
      if: ${{ github.ref == 'refs/heads.main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN  }}
        publish_dir: ./build      

